# Generated by Django 4.2.5 on 2023-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.IntegerField(choices=[(3, 'admin'), (2, 'writer'), (1, 'user')], default=3),
        ),
    ]
