# Generated by Django 4.2.5 on 2023-09-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=' ', max_length=50)),
                ('last_name', models.CharField(default=' ', max_length=50)),
                ('date_of_birth', models.DateField(default='1945-08-02')),
                ('date_of_death', models.DateField(default='2000-02-03')),
                ('where_be_born', models.CharField(default=' ', max_length=100)),
                ('where_die', models.CharField(default=' ', max_length=100)),
                ('description', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('pages', models.IntegerField(default=200)),
                ('publication_date', models.DateField(default='2004-10-02')),
                ('price', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiblar.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='BooksCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiblar.booksmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiblar.authormodel')),
            ],
        ),
    ]
