# Generated by Django 4.2.5 on 2023-09-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adiblar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adiblar.booksmodel')),
            ],
        ),
    ]
