# Generated by Django 4.2.5 on 2023-09-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adiblar', '0003_booksmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='where_die',
            field=models.CharField(default='', max_length=100),
        ),
    ]
